const products = [
  {
    id: "1",
    name: "Macbook Pro",
    description: "A laptop for developers",
    battery: 60,
    price: 2000,
  },
  {
    id: "2",
    name: "Tesla Model S",
    description: "A car for the future",
    battery: 100,
    price: 90000,
  },
  {
    id: "3",
    name: "Wacom Cintiq 22HD",
    description: "A tablet for artists",
    battery: 10,
    price: 1400,
  },
  {
    id: "4",
    name: "Sony A7 III",
    description: "A camera for photographers",
    battery: 14,
    price: 2300,
  },
  {
    id: "5",
    name: "iPhone 12 Pro",
    description: "A phone for everyone",
    battery: 20,
    price: 1000,
  },
  {
    id: "6",
    name: "Google Pixel 5",
    description: "A phone for Android lovers",
    battery: 18,
    price: 700,
  },
  {
    id: "7",
    name: "Samsung Galaxy S21",
    description: "A phone for Samsung fans",
    battery: 15,
    price: 800,
  },
  {
    id: "8",
    name: "iPad Pro",
    description: "A tablet for everyone",
    battery: 12,
    price: 800,
  },
  {
    id: "9",
    name: "Samsung Galaxy Tab S7",
    description: "A tablet for Samsung fans",
    battery: 10,
    price: 700,
  },
  {
    id: "10",
    name: "Dell XPS 13",
    description: "A laptop for everyone",
    battery: 50,
  },
  {
    id: "11",
    name: "HP Spectre x360",
    description: "A laptop for everyone",
    battery: 40,
    price: 1200,
  },
  {
    id: "12",
    name: "Microsoft Surface Pro 7",
    description: "A tablet for everyone",
    battery: 15,
    price: 700,
  },
  {
    id: "13",
    name: "Macbook Air",
    description: "A laptop for everyone",
    battery: 50,
    price: 1000,
  },
  {
    id: "14",
    name: "iPad Air",
    description: "A tablet for everyone",
    battery: 10,
    price: 600,
  },
  {
    id: "15",
    name: "Samsung Galaxy Tab S6",
    description: "A tablet for Samsung fans",
    battery: 10,
    price: 500,
  },
  {
    id: "16",
    name: "Samsung Galaxy Tab S6 Lite",
    description: "A tablet for Samsung fans",
    battery: 10,
    price: 400,
  },
  {
    id: "17",
    name: "Samsung Galaxy Tab A 10.1",
    description: "A tablet for Samsung fans",
    battery: 10,
    price: 300,
  },
  {
    id: "18",
    name: "Samsung Galaxy Tab A 8.0",
    description: "A tablet for Samsung fans",
    battery: 10,
    price: 200,
  },
  {
    id: "19",
    name: "Samsung Galaxy Tab A 7.0",
    description: "A tablet for Samsung fans",
    battery: 10,
    price: 100,
  },
  {
    id: "20",
    name: "Samsung Galaxy Tab A 8.4",
    description: "A tablet for Samsung fans",
    battery: 10,
    price: 150,
  },
];

module.exports = products;
